### ISSUE TITLE
Hi, not an issue, just a question!

### ISSUE THREAD

**Issue by adstyles** [Autapomorph/dino#1]
Love what you've done with this port. I've user Phaser2 for a few games, but this is my first attempt with Phaser 3, so thought I'd use this repo as a guide.

I've tried creating a new style sheet with alternative characters on it using TexturePacker.

The issue I'm having is when using a smart folder, the exported filenames in the JSON have the files/structure/ as part of the filename. What are your texture packer settings? and how can I stop this happening?

**Comment by Autapomorph** [comment]
@adstyles as far as I know there is an option in TexturePacker for trimming file extensions (Advansed settings -> Trim sprite names checkbox). But I don't know about setting for removing file paths

So basically if  you want to use flat in-game file structure (like in this repo) you need to use flat file structure in TexturePacker.
Or you can write a simple nodejs/python/whatever script that will read generated json file and remove prepended filepaths.
Also this is fine to use filenames with paths and extensions inside phaser 'cause it's only a 'title' for adressing sprites in your code

Have a look at this [tutorial](https://www.codeandweb.com/texturepacker/tutorials/how-to-create-sprite-sheets-for-phaser3). Also there is a github repo [link ](https://github.com/CodeAndWeb/TexturePacker-Phaser3) at the end of it with [examples](https://github.com/CodeAndWeb/TexturePacker-Phaser3/blob/master/src/index.js#L26-L33) of using sprites with filepaths and extensions

**Comment by adstyles** [comment]
@Autapomorph this is great, thank you!
